CREATE TABLE IF NOT EXISTS menu(menu_id INTEGER PRIMARY KEY AUTOINCREMENT, menu_code TEXT, menu_name TEXT, menu_color TEXT, menu_img TEXT);
CREATE TABLE IF NOT EXISTS word(word_id INTEGER PRIMARY KEY AUTOINCREMENT, menu_code INTEGER, menu_name TEXT, korean TEXT, chinese TEXT, pronun_ch TEXT, pronun_kr TEXT, is_my_word TEXT);
INSERT or IGNORE INTO menu VALUES (1, 'BASIC', '기초회화', '#fff000', '/asset/img/category/basic.png');
INSERT or IGNORE INTO menu VALUES (2, 'NUMTIME', '숫자/날짜', '#fff001', '/asset/img/category/basic.png');
INSERT or IGNORE INTO menu VALUES (3, 'TRAFFIC', '교통', '#fff002', '/asset/img/category/basic.png');
INSERT or IGNORE INTO menu VALUES (4, 'SHOPPING', '쇼핑', '#fff003', '/asset/img/category/basic.png');
INSERT or IGNORE INTO menu VALUES (5, 'RESTAURANT', '식당', '#fff004', '/asset/img/category/basic.png');
INSERT or IGNORE INTO menu VALUES (6, 'HOTEL', '호텔', '#fff005', '/asset/img/category/basic.png');
INSERT or IGNORE INTO menu VALUES (7, 'EMERGENCY', '비상시', '#fff006', '/asset/img/category/basic.png');
INSERT or IGNORE INTO word VALUES (1, 'BASIC', '기초회화', '나', '我', 'Wǒ', '워', 'N');
INSERT or IGNORE INTO word VALUES (2, 'BASIC', '기초회화', '너', '你', 'Nǐ', '니', 'N');
INSERT or IGNORE INTO word VALUES (3, 'BASIC', '기초회화', '우리', '我们', 'Wǒmen', '워먼', 'N');
INSERT or IGNORE INTO word VALUES (4, 'BASIC', '기초회화', '여자를 부를 때 (아가씨)', '小姐', 'Xiǎojiě', '샤오지에', 'N');
INSERT or IGNORE INTO word VALUES (5, 'BASIC', '기초회화', '남자를 부를 때', '先生', 'Xiānshēng', '씨엔 셩', 'N');
INSERT or IGNORE INTO word VALUES (6, 'BASIC', '기초회화', '안녕하세요', '您好', 'Nín hǎo', '닌하오', 'N');
INSERT or IGNORE INTO word VALUES (7, 'BASIC', '기초회화', '안녕히 계세요', '再见', 'Zàijiàn', '짜이 지엔', 'N');
INSERT or IGNORE INTO word VALUES (8, 'BASIC', '기초회화', '고맙습니다.', '谢谢', 'Xièxiè', '씨에씨에', 'N');
INSERT or IGNORE INTO word VALUES (9, 'BASIC', '기초회화', '죄송합니다.', '不好意思', 'Bù hǎoyìsi', '뿌하오이쓰', 'N');
INSERT or IGNORE INTO word VALUES (10, 'BASIC', '기초회화', '이름이 뭐예요?', '你叫什么名字', 'Nǐ jiào shénme míngzì', '니 쟈오 션머 밍 쯔', 'N');
INSERT or IGNORE INTO word VALUES (11, 'BASIC', '기초회화', '내 이름은 XXX입니다.', '我叫XXX', 'Wǒ jiào XXX', '워 지아오 XXX', 'N');
INSERT or IGNORE INTO word VALUES (12, 'BASIC', '기초회화', '네', '是', 'Shì', '싀', 'N');
INSERT or IGNORE INTO word VALUES (13, 'BASIC', '기초회화', '아니요.', '不是', 'Bùshì', '부싀', 'N');
INSERT or IGNORE INTO word VALUES (14, 'BASIC', '기초회화', '맞습니다.', '对', 'Duì', '뚜웨이', 'N');
INSERT or IGNORE INTO word VALUES (15, 'BASIC', '기초회화', '틀립니다.', '不对', 'Bùduì', '부 뚜웨이', 'N');
INSERT or IGNORE INTO word VALUES (16, 'BASIC', '기초회화', '좋습니다.', '好的', 'Hǎo de', '하오더', 'N');
INSERT or IGNORE INTO word VALUES (17, 'BASIC', '기초회화', '도와주세요.', '请您帮帮我', 'Qǐng nín bāng bāng wǒ', '칭 닌 빵빵 워', 'N');
INSERT or IGNORE INTO word VALUES (18, 'BASIC', '기초회화', '말씀 좀 여쭐게요.', '请问一下', 'Qǐngwèn yīxià', '칭웬 이 시아', 'N');
INSERT or IGNORE INTO word VALUES (19, 'BASIC', '기초회화', '잘 모르겠어요', '我不知道', 'Wǒ bù zhīdào', '워 뿌 쥐다오', 'N');
INSERT or IGNORE INTO word VALUES (20, 'BASIC', '기초회화', '잠깐만요.', '等等', 'Děng děng', '덩덩', 'N');
INSERT or IGNORE INTO word VALUES (21, 'NUMTIME', '숫자/날짜', '0', '零', 'Líng', '링', 'N');
INSERT or IGNORE INTO word VALUES (22, 'NUMTIME', '숫자/날짜', '1', '一', 'Yī', '이', 'N');
INSERT or IGNORE INTO word VALUES (23, 'NUMTIME', '숫자/날짜', '2', '二', '(Èr)', '알', 'N');
INSERT or IGNORE INTO word VALUES (24, 'NUMTIME', '숫자/날짜', '3', '三', '(Sān)', '싼', 'N');
INSERT or IGNORE INTO word VALUES (25, 'NUMTIME', '숫자/날짜', '4', '四', 'Sì)', '쓰', 'N');
INSERT or IGNORE INTO word VALUES (26, 'NUMTIME', '숫자/날짜', '5', '五', 'Wǔ', '우', 'N');
INSERT or IGNORE INTO word VALUES (27, 'NUMTIME', '숫자/날짜', '6', '六', 'Liù', '리어우', 'N');
INSERT or IGNORE INTO word VALUES (28, 'NUMTIME', '숫자/날짜', '7', '七', 'Qī', '치', 'N');
INSERT or IGNORE INTO word VALUES (29, 'NUMTIME', '숫자/날짜', '8', '八', 'Bā', '빠', 'N');
INSERT or IGNORE INTO word VALUES (30, 'NUMTIME', '숫자/날짜', '9', '九', 'Jiǔ', '지어우', 'N');
INSERT or IGNORE INTO word VALUES (31, 'NUMTIME', '숫자/날짜', '10', '十', 'Shí', '싀', 'N');
INSERT or IGNORE INTO word VALUES (32, 'NUMTIME', '숫자/날짜', '11', '十一', 'Shíyī', '싀이', 'N');
INSERT or IGNORE INTO word VALUES (33, 'NUMTIME', '숫자/날짜', '12', '十二', 'Shíèr', '싀알', 'N');
INSERT or IGNORE INTO word VALUES (34, 'NUMTIME', '숫자/날짜', '20', '二十', 'Èrshí', '알싀', 'N');
INSERT or IGNORE INTO word VALUES (35, 'NUMTIME', '숫자/날짜', '30', '三十', 'Sānshí', '싼싀', 'N');
INSERT or IGNORE INTO word VALUES (36, 'NUMTIME', '숫자/날짜', '100', '一百', 'Yībǎi', '이바이', 'N');
INSERT or IGNORE INTO word VALUES (37, 'NUMTIME', '숫자/날짜', '1000', '一千', 'Yīqiān', '이치엔', 'N');
INSERT or IGNORE INTO word VALUES (38, 'NUMTIME', '숫자/날짜', '10000', '一万', 'Yī wàn', '이완', 'N');
INSERT or IGNORE INTO word VALUES (39, 'NUMTIME', '숫자/날짜', '한개', '一个', 'Yīgè', '이끄어', 'N');
INSERT or IGNORE INTO word VALUES (40, 'NUMTIME', '숫자/날짜', '세개', '三个', 'Sān gè', '싼끄어', 'N');
INSERT or IGNORE INTO word VALUES (41, 'NUMTIME', '숫자/날짜', '이틀', '两天', 'Liǎng tiān', '량티엔', 'N');
INSERT or IGNORE INTO word VALUES (42, 'NUMTIME', '숫자/날짜', '5일', '五天', 'Wǔ tiān', '우티엔', 'N');
INSERT or IGNORE INTO word VALUES (43, 'NUMTIME', '숫자/날짜', '일주일', '一个星期', 'Yīgè xīngqí', '이끄어 씽치', 'N');
INSERT or IGNORE INTO word VALUES (44, 'NUMTIME', '숫자/날짜', '10일', '十天', 'Shí tiān', '스티엔', 'N');
INSERT or IGNORE INTO word VALUES (45, 'TRAFFIC', '교통', '전철역이 어디에요?', '地铁站站哪儿', 'Zuìjìn dì dìtiě zhàn', '디티에 짠 짠 날', 'N');
INSERT or IGNORE INTO word VALUES (46, 'TRAFFIC', '교통', '버스정류장은 어디에요?', '公共汽车站哪儿', 'Gōnggòng qìchē zhàn nàer', '꽁공 츼처 짠 날', 'N');
INSERT or IGNORE INTO word VALUES (47, 'TRAFFIC', '교통', '표는 어디에서 사나요?', '在什么地方买票', 'Zài shénme dìfāng mǎi piào', '짜이 션머 띠팡 마이 피아오', 'N');
INSERT or IGNORE INTO word VALUES (48, 'TRAFFIC', '교통', '차를 세워 주세요.', '请停车', 'Qǐng tíngchē', '칭 팅 츠어', 'N');
INSERT or IGNORE INTO word VALUES (49, 'TRAFFIC', '교통', '~까지 가는 데 얼마에요 ?', '到(장소)多少钱？', 'dào duōshǎo qián ?', '따오~뚜어샤오 치앤?', 'N');
INSERT or IGNORE INTO word VALUES (50, 'TRAFFIC', '교통', '~까지 가는 데 얼마나 걸리나요 ?', '到(장소)需要多长时间？', 'dào xūyào duō cháng shíjiān?', '따오~씌야오 뚜어창씌찌앤?', 'N');
INSERT or IGNORE INTO word VALUES (51, 'TRAFFIC', '교통', '트렁크 좀 열어주세요', '请把备箱打开一下', 'qǐng bǎ bèixiāng dǎkāi yíxià', '칭빠 뻬이씨앙 다카이 이씨아', 'N');
INSERT or IGNORE INTO word VALUES (52, 'SHOPPING', '쇼핑', '얼마예요?', '这个多少钱', 'Zhège duōshǎo qián', '', 'N');
INSERT or IGNORE INTO word VALUES (53, 'SHOPPING', '쇼핑', '계산을 부탁합니다.', '请结张', 'Qǐng jié zhāng', '', 'N');
INSERT or IGNORE INTO word VALUES (54, 'SHOPPING', '쇼핑', '신용카드 됩니까?', '刷卡可以吗', 'Shuākǎ kěyǐ ma', '수아 카 커이 마', 'N');
INSERT or IGNORE INTO word VALUES (55, 'SHOPPING', '쇼핑', '계산이 잘못된 것 같아요.', '好像计算错了', 'Hǎoxiàng jìsuàn cuòle', '하오샹 지수안 츠월러', 'N');
INSERT or IGNORE INTO word VALUES (56, 'SHOPPING', '쇼핑', '너무 비싸요.', '太贵了', 'Tài guìle', '타이 꾸일러', 'N');
INSERT or IGNORE INTO word VALUES (57, 'SHOPPING', '쇼핑', '좀 깎아 주세요', '便宜一点', 'Piányí yīdiǎn', '피엔이 이 디엔', 'N');
INSERT or IGNORE INTO word VALUES (58, 'SHOPPING', '쇼핑', '필요 없습니다.', '不要', 'Bùyào', '뿌 야오', 'N');
INSERT or IGNORE INTO word VALUES (59, 'RESTAURANT', '식당', '메뉴를 보고 싶어요.', '我要看菜单', 'Wǒ yào kàn càidān', '워 야오 칸 차이 딴', 'N');
INSERT or IGNORE INTO word VALUES (60, 'RESTAURANT', '식당', '주문이요.', '买单', 'Mǎidān', '마이 딴', 'N');
INSERT or IGNORE INTO word VALUES (61, 'RESTAURANT', '식당', '이것 주세요.', '请给我这个', 'Qǐng gěi wǒ zhège', '칭 게이 워 쩌거', 'N');
INSERT or IGNORE INTO word VALUES (62, 'RESTAURANT', '식당', '고수는 넣지 마세요.', '不要香菜', 'Bùyào xiāngcài', '부 야오 씨앙차이', 'N');
INSERT or IGNORE INTO word VALUES (63, 'RESTAURANT', '식당', '밥 좀 주세요.', '请给我米饭', 'Qǐng gěi wǒ mǐfàn', '칭 게이 워 미 판', 'N');
INSERT or IGNORE INTO word VALUES (64, 'RESTAURANT', '식당', '물 좀 주세요.', '请给我水', 'Qǐng gěi wǒ shuǐ', '칭 게이 워 수웨이', 'N');
INSERT or IGNORE INTO word VALUES (65, 'RESTAURANT', '식당', '맛있어요.', '好吃', 'Hào chī', '하오 취', 'N');
INSERT or IGNORE INTO word VALUES (66, 'RESTAURANT', '식당', '화장실은 어디예요?', '卫生间在哪儿', 'Wèishēngjiān zài nǎer', '웨이셩 지엔 짜이 나알', 'N');
INSERT or IGNORE INTO word VALUES (67, 'RESTAURANT', '식당', '추천해주세요', '给我推荐一下。', 'gěi wǒ tuījiàn yíxià ', '게이워 투에이찌앤 이씨아', 'N');
INSERT or IGNORE INTO word VALUES (68, 'RESTAURANT', '식당', '포장해주세요', '我要打包', 'wǒ yào dǎbāo', '워야오 다바오', 'N');
INSERT or IGNORE INTO word VALUES (69, 'RESTAURANT', '식당', '계산해주세요', '请结账', 'qǐng jiézhàng', '칭 지에장', 'N');
INSERT or IGNORE INTO word VALUES (70, 'RESTAURANT', '식당', '우리 요리는 언제 나오나요?', '我们的菜什么时候上', 'Wǒmen de cài shí me shíhòu shàng', '워 먼 더 차이 션머 스 호우 샹', 'N');
INSERT or IGNORE INTO word VALUES (71, 'RESTAURANT', '식당', '맥주를 주시겠습니까?', '请给我啤酒?', 'Qǐng gěi wǒ píjiǔ?', '칭께워 피져우', 'N');
INSERT or IGNORE INTO word VALUES (72, 'RESTAURANT', '식당', '물 한 잔 주세요', '请给我一杯水', 'Qǐng gěi wǒ yībēi shuǐ', '칭 게이 워 이 뻬이 수이', 'N');
INSERT or IGNORE INTO word VALUES (73, 'RESTAURANT', '식당', '젓가락을 떨어뜨렸습니다.', '筷子掉了。', 'Kuàizi diàole.', '', 'N');
INSERT or IGNORE INTO word VALUES (74, 'RESTAURANT', '식당', '신용카드도 됩니까?', '刷卡可以吗', 'Shuākǎ kěyǐ ma', '수아카 커이마', 'N');
INSERT or IGNORE INTO word VALUES (75, 'RESTAURANT', '식당', '어떤 요리가 좋습니까?', '有什么好菜', 'Yǒu shé me hǎo cài', '이요우 션머 하오차이', 'N');
INSERT or IGNORE INTO word VALUES (76, 'RESTAURANT', '식당', '맥주를 1 병 더 주십시오', '还要一瓶啤酒', 'Hái yào yī píng píjiǔ', '하이 야오 이핑 피지우', 'N');
INSERT or IGNORE INTO word VALUES (77, 'RESTAURANT', '식당', '차가운 물 좀 주세요.', '请给我冰镇的矿泉水', 'Qǐng gěi wǒ bīng zhèn de kuàng quán shuǐ', '칭게이워 삥쩐더 쾅췐쉐이', 'N');
INSERT or IGNORE INTO word VALUES (78, 'RESTAURANT', '식당', '밥', '米饭', 'Mǐfàn', '미 판', 'N');
INSERT or IGNORE INTO word VALUES (79, 'RESTAURANT', '식당', '국', '汤', 'Tāng', '탕', 'N');
INSERT or IGNORE INTO word VALUES (80, 'RESTAURANT', '식당', '볶음밥', '炒饭', 'Chǎofàn', '차오 판', 'N');
INSERT or IGNORE INTO word VALUES (81, 'RESTAURANT', '식당', '볶음면', '炒面', 'Chǎomiàn', '차오 미엔', 'N');
INSERT or IGNORE INTO word VALUES (82, 'RESTAURANT', '식당', '국수', '面条', 'Miàntiáo', '미엔 티아오', 'N');
INSERT or IGNORE INTO word VALUES (83, 'RESTAURANT', '식당', '만두', '包子', 'Bāozi', '바오 쯔', 'N');
INSERT or IGNORE INTO word VALUES (84, 'RESTAURANT', '식당', '빵', '面包', 'Miànbāo', '미엔 빠오', 'N');
INSERT or IGNORE INTO word VALUES (85, 'RESTAURANT', '식당', '돼지고기', '猪肉', 'Zhūròu', '쭈 로우', 'N');
INSERT or IGNORE INTO word VALUES (86, 'RESTAURANT', '식당', '소고기', '牛肉', 'Niúròu', '니여우 로우', 'N');
INSERT or IGNORE INTO word VALUES (87, 'RESTAURANT', '식당', '닭고기', '鸡肉', 'Jīròu', '지 로우', 'N');
INSERT or IGNORE INTO word VALUES (88, 'RESTAURANT', '식당', '양고기', '羊肉', 'Yángròu', '양 로우', 'N');
INSERT or IGNORE INTO word VALUES (89, 'RESTAURANT', '식당', '숟가락', '汤匙', 'Tāngchí', '탕 취', 'N');
INSERT or IGNORE INTO word VALUES (90, 'RESTAURANT', '식당', '젓가락', '筷子', 'Kuàizi', '콰이 쯔', 'N');
INSERT or IGNORE INTO word VALUES (91, 'HOTEL', '호텔', '더운 물이 나오지 않습니다.', '不出热水', 'Bù chū rè shuǐ', '뿌 추러 쉐이', 'N');
INSERT or IGNORE INTO word VALUES (92, 'HOTEL', '호텔', '에어콘이 작동되지 않습니다.', '空调坏了', 'Kòngtiáo huàile', '쿵 티아오 파일 러', 'N');
INSERT or IGNORE INTO word VALUES (93, 'HOTEL', '호텔', '수건을 바꿔주세요.', '请给我一些毛巾', 'Qǐng bāng wǒ huàn máojīn', '칭빵워 환 마오진', 'N');
INSERT or IGNORE INTO word VALUES (94, 'HOTEL', '호텔', '방을 바꿔주세요.', '请给我换房间', 'Qǐng gěi wǒ huàn fángjiān', '칭게이워 환 팡지엔', 'N');
INSERT or IGNORE INTO word VALUES (95, 'HOTEL', '호텔', '체크아웃하겠습니다.', '请给我退房', 'Qǐng gěi wǒ tuì fáng', '칭게이워 투이팡', 'N');
INSERT or IGNORE INTO word VALUES (96, 'HOTEL', '호텔', '체크인 부탁합니다.', '请给我开个房间', 'Qǐng gěi wǒ kāi gè fángjiān', '칭게이워 카이거 팡지엔', 'N');
INSERT or IGNORE INTO word VALUES (97, 'HOTEL', '호텔', '예약했습니다.', '预约了', 'Yùyuēle', '위위에러', 'N');
INSERT or IGNORE INTO word VALUES (98, 'EMERGENCY', '비상시', '길을 잃었습니다', '我迷路了', 'Wǒ mílùle', '워미루러', 'N');


-- CREATE TABLE IF NOT EXISTS menu(menu_id INTEGER PRIMARY KEY AUTOINCREMENT, menu_code TEXT, menu_name TEXT, menu_color TEXT, menu_img TEXT);
-- INSERT or IGNORE INTO menu VALUES (1, 'BASIC', '기본', '#fff000', '/assets/img/menu/basic.png');

-- CREATE TABLE IF NOT EXISTS word(word_id INTEGER PRIMARY KEY AUTOINCREMENT, menu_code INTEGER, menu_name TEXT, korean TEXT, chinese TEXT, pronun_ch TEXT, pronun_kr TEXT, is_my_word TEXT);
-- INSERT or IGNORE INTO word VALUES (1, 'BASIC', '기본', '나', '중국어', 'na', '나', 'N');